// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * @returns {Promise<string> & { cancel(): void }}
 */
export function ConvertVideo() {
    let $resultPromise = /** @type {any} */($Call.ByID(1727164232));
    return $resultPromise;
}

/**
 * @returns {Promise<string[]> & { cancel(): void }}
 */
export function UploadFile() {
    let $resultPromise = /** @type {any} */($Call.ByID(970375137));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
